import XCTest
@testable import RemoteBridge

final class ClaudeTranscriptSessionTests: XCTestCase {
    func testClaudeLocalCommandEnvelopeUserMessagesAreNotPublished() throws {
        let directory = FileManager.default.temporaryDirectory
            .appendingPathComponent("ClaudeTranscriptSessionTests-\(UUID().uuidString)", isDirectory: true)
        try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: directory) }

        let transcriptURL = directory.appendingPathComponent("session.jsonl", isDirectory: false)
        let envelopeLines = [
            makeClaudeUserLine(uuid: "u1", content: "<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages or otherwise consider them in your response unless the user explicitly asks you to.</local-command-caveat>"),
            makeClaudeUserLine(uuid: "u2", content: "<command-name>/exit</command-name> <command-message>exit</command-message> <command-args></command-args>"),
            makeClaudeUserLine(uuid: "u3", content: "<local-command-stdout>Goodbye!</local-command-stdout>"),
        ].joined(separator: "\n") + "\n"
        try envelopeLines.write(to: transcriptURL, atomically: true, encoding: .utf8)

        let hub = AgentEventHub()
        let session = ClaudeTranscriptSession(record: makeRecord(transcriptPath: transcriptURL.path),
                                              fileManager: .default,
                                              hub: hub)
        session.start()
        defer { session.stop() }

        XCTAssertTrue(waitUntil {
            let result = hub.fetch(workspaceID: "workspace",
                                   sessionID: "session",
                                   limit: 10,
                                   beforeSeq: nil,
                                   afterSeq: nil)
            return result.events.contains { $0.type == .sessionStarted }
        })

        let result = hub.fetch(workspaceID: "workspace",
                               sessionID: "session",
                               limit: 10,
                               beforeSeq: nil,
                               afterSeq: nil)
        XCTAssertEqual(result.events.map(\.type), [.sessionStarted])
        XCTAssertFalse(result.events.contains { ($0.text ?? "").contains("local-command") })
        XCTAssertFalse(result.events.contains { ($0.text ?? "").contains("/exit") })
    }

    func testClaudeRegularSlashLikeUserTextStillPublishes() throws {
        let directory = FileManager.default.temporaryDirectory
            .appendingPathComponent("ClaudeTranscriptSessionTests-\(UUID().uuidString)", isDirectory: true)
        try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: directory) }

        let transcriptURL = directory.appendingPathComponent("session.jsonl", isDirectory: false)
        try makeClaudeUserLine(uuid: "u1", content: "Please explain when to use /exit in docs.")
            .appending("\n")
            .write(to: transcriptURL, atomically: true, encoding: .utf8)

        let hub = AgentEventHub()
        let session = ClaudeTranscriptSession(record: makeRecord(transcriptPath: transcriptURL.path),
                                              fileManager: .default,
                                              hub: hub)
        session.start()
        defer { session.stop() }

        XCTAssertTrue(waitUntil {
            let result = hub.fetch(workspaceID: "workspace",
                                   sessionID: "session",
                                   limit: 10,
                                   beforeSeq: nil,
                                   afterSeq: nil)
            return result.events.contains { $0.type == .userMessage }
        })

        let result = hub.fetch(workspaceID: "workspace",
                               sessionID: "session",
                               limit: 10,
                               beforeSeq: nil,
                               afterSeq: nil)
        XCTAssertEqual(result.events.compactMap(\.text), ["Please explain when to use /exit in docs."])
    }

    func testClaudeContextCommandPublishesCleanGeneratedSummary() throws {
        let directory = FileManager.default.temporaryDirectory
            .appendingPathComponent("ClaudeTranscriptSessionTests-\(UUID().uuidString)", isDirectory: true)
        try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: directory) }

        let transcriptURL = directory.appendingPathComponent("session.jsonl", isDirectory: false)
        let lines = [
            makeClaudeUserLine(uuid: "u1", content: "<command-name>/context</command-name>\n<command-message>context</command-message>\n<command-args></command-args>"),
            makeClaudeUserLine(uuid: "u2", content: "<local-command-stdout> \u{001B}[1mContext Usage\u{001B}[22m\n◉ ◉ ◉ Opus 4.7 (1M context)\n◉ ◉ ◉ 399.1k/1m tokens (40%)\n▢ ▢ ▢ Estimated usage by category\n◉ System prompt: 8.3k tokens (0.8%)\n◉ System tools: 5.5k tokens (0.5%)\n◉ Memory files: 3.5k tokens (0.3%)\n◉ Skills: 7.2k tokens (0.7%)\n◉ Messages: 376.8k tokens (37.7%)\n▢ Free space: 598.8k (59.9%)\nMCP tools: /mcp (loaded on-demand)\nAvailable\n├ benchmark: 103 tokens</local-command-stdout>"),
        ].joined(separator: "\n") + "\n"
        try lines.write(to: transcriptURL, atomically: true, encoding: .utf8)

        let hub = AgentEventHub()
        let session = ClaudeTranscriptSession(record: makeRecord(transcriptPath: transcriptURL.path),
                                              fileManager: .default,
                                              hub: hub)
        session.start()
        defer { session.stop() }

        XCTAssertTrue(waitUntil {
            let result = hub.fetch(workspaceID: "workspace",
                                   sessionID: "session",
                                   limit: 10,
                                   beforeSeq: nil,
                                   afterSeq: nil)
            return result.events.contains { $0.metadata?["tidey_generated"] == "claude_context" }
        })

        let result = hub.fetch(workspaceID: "workspace",
                               sessionID: "session",
                               limit: 10,
                               beforeSeq: nil,
                               afterSeq: nil)
        let contextEvent = try XCTUnwrap(result.events.first { $0.metadata?["tidey_generated"] == "claude_context" })
        XCTAssertEqual(contextEvent.type, .assistantMessage)
        XCTAssertEqual(contextEvent.role, "assistant")
        XCTAssertEqual(contextEvent.metadata?["slash_command"], "/context")
        XCTAssertTrue((contextEvent.text ?? "").contains("### Claude Context"))
        XCTAssertTrue((contextEvent.text ?? "").contains("Opus 4.7 - 1M context"))
        XCTAssertTrue((contextEvent.text ?? "").contains("`[########------------]` 40%"))
        XCTAssertTrue((contextEvent.text ?? "").contains("399.1k / 1m used - 598.8k free"))
        XCTAssertTrue((contextEvent.text ?? "").contains("- Messages: `[########------------]` 37.7% - 376.8k"))
        XCTAssertTrue((contextEvent.text ?? "").contains("- System prompt: `[--------------------]` 0.8% - 8.3k"))
        XCTAssertFalse((contextEvent.text ?? "").contains("local-command-stdout"))
        XCTAssertFalse((contextEvent.text ?? "").contains("Available"))
        XCTAssertFalse((contextEvent.text ?? "").contains("benchmark"))
        XCTAssertFalse((contextEvent.text ?? "").contains("MCP tools"))
        XCTAssertFalse((contextEvent.text ?? "").contains("\u{001B}"))
        XCTAssertFalse(result.events.contains { ($0.text ?? "").contains("<command-name>") })
    }

    func testClaudeLocalCommandStdoutWithoutContextCommandIsNotPublished() throws {
        let directory = FileManager.default.temporaryDirectory
            .appendingPathComponent("ClaudeTranscriptSessionTests-\(UUID().uuidString)", isDirectory: true)
        try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: directory) }

        let transcriptURL = directory.appendingPathComponent("session.jsonl", isDirectory: false)
        let lines = [
            makeClaudeUserLine(uuid: "u1", content: "<command-name>/exit</command-name><command-message>exit</command-message><command-args></command-args>"),
            makeClaudeUserLine(uuid: "u2", content: "<local-command-stdout>Goodbye!</local-command-stdout>"),
        ].joined(separator: "\n") + "\n"
        try lines.write(to: transcriptURL, atomically: true, encoding: .utf8)

        let hub = AgentEventHub()
        let session = ClaudeTranscriptSession(record: makeRecord(transcriptPath: transcriptURL.path),
                                              fileManager: .default,
                                              hub: hub)
        session.start()
        defer { session.stop() }

        XCTAssertTrue(waitUntil {
            let result = hub.fetch(workspaceID: "workspace",
                                   sessionID: "session",
                                   limit: 10,
                                   beforeSeq: nil,
                                   afterSeq: nil)
            return result.events.contains { $0.type == .sessionStarted }
        })

        let result = hub.fetch(workspaceID: "workspace",
                               sessionID: "session",
                               limit: 10,
                               beforeSeq: nil,
                               afterSeq: nil)
        XCTAssertEqual(result.events.map(\.type), [.sessionStarted])
    }

    func testClaudeUserEchoConsumesClientRequestIDMetadata() throws {
        let directory = FileManager.default.temporaryDirectory
            .appendingPathComponent("ClaudeTranscriptSessionTests-\(UUID().uuidString)", isDirectory: true)
        try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: directory) }

        let transcriptURL = directory.appendingPathComponent("session.jsonl", isDirectory: false)
        try makeClaudeUserLine(uuid: "u1", content: "hello from remote")
            .appending("\n")
            .write(to: transcriptURL, atomically: true, encoding: .utf8)

        let registry = ChatSubmitEchoRegistry()
        registry.register(workspaceID: "workspace",
                          panelID: "panel",
                          sessionID: "session",
                          vendor: "claude",
                          text: "hello from remote",
                          clientRequestID: "local-1")

        let hub = AgentEventHub()
        let session = ClaudeTranscriptSession(record: makeRecord(transcriptPath: transcriptURL.path),
                                              fileManager: .default,
                                              hub: hub,
                                              chatSubmitEchoRegistry: registry)
        session.start()
        defer { session.stop() }

        XCTAssertTrue(waitUntil {
            let result = hub.fetch(workspaceID: "workspace",
                                   sessionID: "session",
                                   limit: 10,
                                   beforeSeq: nil,
                                   afterSeq: nil)
            return result.events.contains { $0.metadata?["client_request_id"] == "local-1" }
        })

        let result = hub.fetch(workspaceID: "workspace",
                               sessionID: "session",
                               limit: 10,
                               beforeSeq: nil,
                               afterSeq: nil)
        let userEvent = try XCTUnwrap(result.events.first { $0.type == .userMessage })
        XCTAssertEqual(userEvent.metadata?["client_request_id"], "local-1")
        XCTAssertTrue(registry.snapshot().isEmpty)
    }

    private func makeRecord(transcriptPath: String) -> AgentSessionRegistryRecord {
        AgentSessionRegistryRecord(version: 1,
                                   vendor: "claude",
                                   workspaceID: "workspace",
                                   sessionID: "session",
                                   panelID: "panel",
                                   pid: Int32(ProcessInfo.processInfo.processIdentifier),
                                   cwd: "/tmp",
                                   createdAt: "2026-04-30T00:00:00Z",
                                   transcriptPath: transcriptPath)
    }

    private func makeClaudeUserLine(uuid: String, content: String) -> String {
        let object: [String: Any] = [
            "type": "user",
            "uuid": uuid,
            "sessionId": "session",
            "version": "2.0.0",
            "timestamp": "2026-04-30T00:00:00Z",
            "message": [
                "role": "user",
                "content": content,
            ],
        ]
        let data = try! JSONSerialization.data(withJSONObject: object, options: [.sortedKeys])
        return String(data: data, encoding: .utf8)!
    }

    private func waitUntil(timeout: TimeInterval = 2,
                           condition: () -> Bool) -> Bool {
        let deadline = Date().addingTimeInterval(timeout)
        while Date() < deadline {
            if condition() {
                return true
            }
            RunLoop.current.run(mode: .default, before: Date().addingTimeInterval(0.01))
        }
        return condition()
    }
}
